### PR TITLE
Add enumerable functions

### PR DESCRIPTION
**Pull request by houdamzari**
- [x] Creating a module MyEnumerable that implements the following methods :
    #all?
    #any?
    #filter

- [x] Creating the list class.
- [x] All linters are passing.

### CODE REVIEW

**Review by mckent05 — COMMENTED** [review]
Hi @houdamzari, 

# STATUS: INVALID REQUEST ❌ ❌ 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that uses the wrong workflow. For this milestone, you are expected to use Gitflow i.e your PR should merge from a `feature` branch into the `development` branch, which is expected to be your base branch. Please fix this 🙏 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by houdamzari** [comment]
@mckent05  Kindly check the requirements. https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md

**Comment by leehaney254** [comment]
Hello! @mckent05
That is not the case according to the requirements. Kindly reconsider as they have requested us to use GitHub flow.
github

**Review by DammyShittu — APPROVED** [review]
Hi @houdamzari and @leehaney254,

## APPROVED 🟢

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
